# Generated by Django 5.1.3 on 2024-12-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scopesubapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=10)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phn', models.CharField(max_length=20)),
                ('country', models.CharField(choices=[('US', 'United States'), ('CA', 'Canada'), ('UK', 'United Kingdom'), ('IN', 'India'), ('AU', 'Australia')], max_length=30)),
                ('state', models.CharField(choices=[('AP', 'Andhra Pradhesh'), ('OD', 'Odissa'), ('KL', 'Kerala'), ('TN', 'Tamil Nadu'), ('WB', 'West Bengal')], max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('hobbies', models.CharField(choices=[('reading', 'Reading'), ('sports', 'Sports'), ('travel', 'Travelling')], max_length=30)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
