# Generated by Django 5.1.3 on 2024-12-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scopesubapp', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='file',
            field=models.FileField(null=True, upload_to='mydocs'),
        ),
    ]
