# Generated by Django 5.1.3 on 2025-01-16 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scopesubapp', '0004_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='file',
            new_name='avatar',
        ),
    ]
