# Generated by Django 5.1.3 on 2025-02-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scopesubapp', '0005_rename_file_student_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='country',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='hobbies',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='state',
            field=models.CharField(max_length=30),
        ),
    ]
