# Generated by Django 5.1.3 on 2025-02-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scopesubapp', '0006_alter_student_country_alter_student_hobbies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(default='FirstName', max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(default='LastName', max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='default_username', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='hobbies',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='phn',
            field=models.CharField(max_length=15),
        ),
    ]
