# Generated by Django 5.1.3 on 2025-02-12 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scopesubapp', '0007_customuser_first_name_customuser_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
