# Generated by Django 5.1.3 on 2025-02-19 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scopesubapp', '0009_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
